#!/bin/bash
# Generate src/jit/wasm_symtab.c inside the nvc submodule.
#
# nvc's internal runtime symbols (in symbols.txt) are normally resolved via
# dlsym(NULL, name) against the executable's dynamic symbol table. Wasm has
# no such table, so we build a static (name -> function pointer) table that
# our patched jit-ffi.c consults instead.
set -euo pipefail

NVC_SRC="${1:-$PWD/3rdparty/nvc}"
SYMS="$NVC_SRC/src/symbols.txt"
OUT="$NVC_SRC/src/jit/wasm_symtab.c"

if [ ! -f "$SYMS" ]; then
   echo "error: $SYMS not found" >&2
   exit 1
fi

{
   echo "// Auto-generated by scripts/gen_wasm_symtab.sh - do not edit."
   echo "#include <string.h>"
   echo "#include <stddef.h>"
   echo "#include \"jit/jit.h\""
   echo "#include \"jit/jit-ffi.h\""
   echo
   grep -E '^\s+_' "$SYMS" | sed 's/[; ]//g' | while read -r sym; do
      [ -n "$sym" ] && echo "extern void $sym(jit_scalar_t *args, tlab_t *tlab);"
   done
   echo
   echo "struct nvc_wasm_sym { const char *name; void *ptr; };"
   echo "static const struct nvc_wasm_sym nvc_wasm_syms[] = {"
   grep -E '^\s+_' "$SYMS" | sed 's/[; ]//g' | while read -r sym; do
      [ -n "$sym" ] && echo "   { \"$sym\", (void *)$sym },"
   done
   echo "   { NULL, NULL }"
   echo "};"
   echo
   echo "void *nvc_wasm_dlsym(const char *name) {"
   echo "   if (name == NULL) return NULL;"
   echo "   for (const struct nvc_wasm_sym *s = nvc_wasm_syms; s->name; s++)"
   echo "      if (strcmp(s->name, name) == 0) return s->ptr;"
   echo "   return NULL;"
   echo "}"
} > "$OUT"

echo "generated: $OUT"
